// AUTO-GENERATED by scripts/gen-sole-profiles.mjs from "Zolen Piedro.xlsx". Do not edit by hand.
// Per-group allowed canonical values for the sole-amendment config fields.
// A field absent from a group = HIDDEN for that group. spoiler is never used by Zolen.
// Group 3 (Runner): runner_sole intentionally UNRESTRICTED ("Runner soles all", pending Anabela).
// NEW values dropped (pending Dataverse codes): see docs/sole-hierarchy/zolen-canonical-map.md.

export const SOLE_GROUP_LABELS: Record<string, string> = {
  "KIDS-NOADJ": "No adjustments",
  "KIDS-CUP": "Cup Sole + High & Mid Tops",
  "KIDS-STITCHED": "Stitched Down",
  "KIDS-TRAINERS": "Trainers",
  "ADULTS-1": "Cupsole OUD Ladies",
  "ADULTS-2": "Cupsole OUD Men",
  "ADULTS-3": "Runner",
  "ADULTS-4": "Sneaker",
  "ADULTS-5": "Klassiek",
  "ADULTS-6": "Diab Klassiek",
  "ADULTS-7": "Cupsole (new) Men",
  "ADULTS-8": "Klassiek Heren",
  "ADULTS-9": "Klassiek Heren 2",
  "ADULTS-10": "No adjustments",
  "ADULTS-11": "Diab Group",
  "ADULTS-12": "Livingstone"
}

// Value '*' = field shown but UNRESTRICTED (sees all). Field absent = hidden for the group.
export const PROFILE_OPTIONS: Record<string, Partial<Record<'pu_type'|'sole_type'|'runner_sole', string[] | '*'>>> = {
  "KIDS-NOADJ": {},
  "KIDS-CUP": {
    "pu_type": [
      "EVA Black",
      "EVA White",
      "PU White",
      "PU Black"
    ],
    "runner_sole": [
      "Fish Black",
      "Fish Amber"
    ]
  },
  "KIDS-STITCHED": {
    "sole_type": [
      "EVA Lightweight Black",
      "EVA Lightweight Off-White",
      "Full Rubber Black",
      "Full Rubber Amber",
      "Full Rubber Blue",
      "Full Rubber Pink",
      "Full Rubber White"
    ]
  },
  "KIDS-TRAINERS": {
    "runner_sole": [
      "Fish Black",
      "Fish Amber"
    ]
  },
  "ADULTS-1": {
    "pu_type": [
      "PU Black",
      "PU White"
    ],
    "runner_sole": [
      "Piedro Runner Black",
      "Piedro Runner Amber",
      "Fish Black",
      "Fish Amber",
      "EVA Nora Astro Star Lightweight Black",
      "EVA Nora Astro Star Lightweight Amber"
    ]
  },
  "ADULTS-2": {
    "pu_type": [
      "PU Black",
      "PU White"
    ],
    "runner_sole": [
      "Piedro Runner Black",
      "Piedro Runner Amber",
      "Fish Black",
      "Fish Amber",
      "EVA Nora Astro Star Lightweight Black",
      "EVA Nora Astro Star Lightweight Amber"
    ]
  },
  "ADULTS-3": {
    "runner_sole": "*"
  },
  "ADULTS-4": {
    "runner_sole": [
      "Piedro Runner Black",
      "Piedro Runner Amber",
      "Fish Black",
      "Fish Amber",
      "EVA Nora Astro Star Lightweight Black",
      "EVA Nora Astro Star Lightweight Amber"
    ]
  },
  "ADULTS-5": {
    "sole_type": [
      "EVA Taupe",
      "EVA Brown",
      "EVA Black"
    ]
  },
  "ADULTS-6": {
    "sole_type": [
      "EVA Lightweight Taupe",
      "EVA Lightweight Black"
    ]
  },
  "ADULTS-7": {
    "pu_type": [
      "EVA Black",
      "EVA White"
    ],
    "runner_sole": [
      "Piedro Runner Black",
      "Piedro Runner Amber",
      "Fish Black",
      "Fish Amber",
      "EVA Nora Astro Star Lightweight Black",
      "EVA Nora Astro Star Lightweight Amber"
    ]
  },
  "ADULTS-8": {
    "runner_sole": [
      "Lightweight Vibram Sole Black",
      "Lightweight Vibram Sole Brown",
      "Lightweight Sole Forli Uomo",
      "Full Rubber Sole Montana Black",
      "Full Rubber Sole Montana Brown"
    ]
  },
  "ADULTS-9": {},
  "ADULTS-10": {},
  "ADULTS-11": {
    "runner_sole": [
      "Fish Black",
      "Fish Amber",
      "EVA Nora Astro Star Lightweight Black",
      "EVA Nora Astro Star Lightweight Amber"
    ]
  },
  "ADULTS-12": {
    "runner_sole": [
      "Lightweight Vibram Sole Black",
      "Lightweight Vibram Sole Brown",
      "Full Rubber Sole Montana Black",
      "Full Rubber Sole Montana Brown"
    ]
  }
}

export const PROFILE_STYLES: Record<string, string[]> = {
  "KIDS-NOADJ": [
    "2299",
    "2301",
    "2309",
    "2212",
    "2213",
    "1700",
    "1701",
    "1702",
    "1800"
  ],
  "KIDS-CUP": [
    "2269",
    "2270",
    "2272",
    "1906",
    "1900",
    "1903",
    "1901",
    "1902",
    "1904",
    "1905",
    "2160",
    "2123",
    "2133",
    "2105",
    "2115",
    "2151",
    "2189",
    "2118",
    "2137",
    "2126"
  ],
  "KIDS-STITCHED": [
    "2303",
    "2312",
    "2314",
    "2315",
    "2310",
    "2316",
    "2504",
    "2482",
    "2492",
    "2488",
    "2407",
    "2483",
    "2484",
    "2480",
    "2489",
    "2601",
    "2604"
  ],
  "KIDS-TRAINERS": [
    "2089",
    "2034",
    "2134",
    "2090",
    "2038",
    "2138",
    "2060",
    "2091",
    "2092"
  ],
  "ADULTS-1": [
    "4800",
    "4318",
    "4610",
    "4590",
    "4580",
    "4527",
    "4523"
  ],
  "ADULTS-2": [
    "3614",
    "3613",
    "3612",
    "3611",
    "3618",
    "3617",
    "3627",
    "3628",
    "3590",
    "3591"
  ],
  "ADULTS-3": [
    "4807",
    "4804",
    "4802",
    "4323",
    "4327",
    "4560",
    "4550",
    "4570",
    "4620",
    "4326",
    "4900",
    "5313",
    "5303",
    "5300",
    "3604",
    "3603",
    "3606",
    "3605",
    "5200",
    "3640",
    "3641"
  ],
  "ADULTS-4": [
    "4801",
    "4808",
    "4810",
    "4803",
    "4809",
    "4901",
    "5315",
    "5314",
    "5305",
    "5302",
    "5311",
    "5316",
    "5201",
    "4571",
    "4621"
  ],
  "ADULTS-5": [
    "3469",
    "3467",
    "3485",
    "4400"
  ],
  "ADULTS-6": [
    "3345",
    "3340",
    "3337",
    "3341",
    "3346",
    "3370",
    "3371",
    "3335",
    "3330",
    "3390",
    "3380",
    "3585",
    "3395",
    "3385",
    "3310",
    "3315"
  ],
  "ADULTS-7": [
    "5312",
    "5304",
    "5301",
    "5310",
    "5308",
    "5309"
  ],
  "ADULTS-8": [
    "3542",
    "3543",
    "3540",
    "3541",
    "3599",
    "3597",
    "3598",
    "3595",
    "3596",
    "3520",
    "3521",
    "3522",
    "3524"
  ],
  "ADULTS-9": [
    "3502",
    "3506",
    "3504",
    "3508"
  ],
  "ADULTS-10": [
    "4701",
    "4700",
    "4322",
    "4320",
    "4321",
    "5306",
    "5202",
    "5203",
    "4903",
    "4904"
  ],
  "ADULTS-11": [
    "5205",
    "5206",
    "5207",
    "5208"
  ],
  "ADULTS-12": [
    "48051",
    "48951",
    "48961"
  ]
}
