-- ============================================
-- POPULATE: color_name_i18n translations
-- ============================================
-- Based on the color translations array from Power Pages
-- Format: UPDATE products SET color_name_i18n = '{"nl": "...", "fr": "...", "de": "..."}'::jsonb
--         WHERE color_name = '...';

-- Note: German (DE) uses Dutch (NL) as fallback as specified

UPDATE products SET color_name_i18n = '{"nl":"Beige","fr":"Beige","de":"Beige"}'::jsonb WHERE color_name = 'Beige';
UPDATE products SET color_name_i18n = '{"nl":"Meerkleurig","fr":"Multicolore","de":"Meerkleurig"}'::jsonb WHERE color_name = 'Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Zwart","fr":"Noir","de":"Zwart"}'::jsonb WHERE color_name = 'Black';
UPDATE products SET color_name_i18n = '{"nl":"Blauw","fr":"Bleu","de":"Blauw"}'::jsonb WHERE color_name = 'Blue';
UPDATE products SET color_name_i18n = '{"nl":"Bruin","fr":"Marron","de":"Bruin"}'::jsonb WHERE color_name = 'Brown';
UPDATE products SET color_name_i18n = '{"nl":"Groen","fr":"Vert","de":"Groen"}'::jsonb WHERE color_name = 'Green';
UPDATE products SET color_name_i18n = '{"nl":"Grijs","fr":"Gris","de":"Grijs"}'::jsonb WHERE color_name = 'Grey';
UPDATE products SET color_name_i18n = '{"nl":"Roze","fr":"Rose","de":"Roze"}'::jsonb WHERE color_name = 'Pink';
UPDATE products SET color_name_i18n = '{"nl":"Rood","fr":"Rouge","de":"Rood"}'::jsonb WHERE color_name = 'Red';
UPDATE products SET color_name_i18n = '{"nl":"Wit","fr":"Blanc","de":"Wit"}'::jsonb WHERE color_name = 'White';
UPDATE products SET color_name_i18n = '{"nl":"Antraciet Cognac Suède","fr":"Anthracite Cognac Daim","de":"Antraciet Cognac Suède"}'::jsonb WHERE color_name = 'Anthracite Cognac Suede';
UPDATE products SET color_name_i18n = '{"nl":"Beige Zwart Suède Mesh","fr":"Beige Noir Daim Mesh","de":"Beige Zwart Suède Mesh"}'::jsonb WHERE color_name = 'Beige Black Suede Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Beige Leer","fr":"Beige Cuir","de":"Beige Leer"}'::jsonb WHERE color_name = 'Beige Leather';
UPDATE products SET color_name_i18n = '{"nl":"Beige Leer Suède","fr":"Beige Cuir Daim","de":"Beige Leer Suède"}'::jsonb WHERE color_name = 'Beige Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Beige Multi Kleur Suède Mesh","fr":"Beige Multicolore Daim Mesh","de":"Beige Multi Kleur Suède Mesh"}'::jsonb WHERE color_name = 'Beige Multi Colour Suede Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Beige Suède","fr":"Beige Daim","de":"Beige Suède"}'::jsonb WHERE color_name = 'Beige Suede';
UPDATE products SET color_name_i18n = '{"nl":"Beige Suède Leer","fr":"Beige Daim Cuir","de":"Beige Suède Leer"}'::jsonb WHERE color_name = 'Beige Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Cognac Leer Suède","fr":"Noir Cognac Cuir Daim","de":"Zwart Cognac Leer Suède"}'::jsonb WHERE color_name = 'Black Cognac Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Koper Leer Suède","fr":"Noir Cuivre Cuir Daim","de":"Zwart Koper Leer Suède"}'::jsonb WHERE color_name = 'Black Copper Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Croco Leer","fr":"Noir Croco Cuir","de":"Zwart Croco Leer"}'::jsonb WHERE color_name = 'Black Croco Leather';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Grijs Nubuck","fr":"Noir Gris Nubuck","de":"Zwart Grijs Nubuck"}'::jsonb WHERE color_name = 'Black Grey Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer","fr":"Noir Cuir","de":"Zwart Leer"}'::jsonb WHERE color_name = 'Black Leather';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Lycra","fr":"Noir Cuir Lycra","de":"Zwart Leer Lycra"}'::jsonb WHERE color_name = 'Black Leather Lycra';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Mesh","fr":"Noir Cuir Mesh","de":"Zwart Leer Mesh"}'::jsonb WHERE color_name = 'Black Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Mesh Lak","fr":"Noir Cuir Mesh Vernis","de":"Zwart Leer Mesh Lak"}'::jsonb WHERE color_name = 'Black Leather Mesh Patent';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Nubuck","fr":"Noir Cuir Nubuck","de":"Zwart Leer Nubuck"}'::jsonb WHERE color_name = 'Black Leather Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Suède","fr":"Noir Cuir Daim","de":"Zwart Leer Suède"}'::jsonb WHERE color_name = 'Black Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Leer Suède Lak","fr":"Noir Cuir Daim Vernis","de":"Zwart Leer Suède Lak"}'::jsonb WHERE color_name = 'Black Leather Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Nubuck","fr":"Noir Nubuck","de":"Zwart Nubuck"}'::jsonb WHERE color_name = 'Black Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Nubuck Leer","fr":"Noir Nubuck Cuir","de":"Zwart Nubuck Leer"}'::jsonb WHERE color_name = 'Black Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Nubuck Lak","fr":"Noir Nubuck Vernis","de":"Zwart Nubuck Lak"}'::jsonb WHERE color_name = 'Black Nubuck Patent';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Off-White Suède Leer Mesh","fr":"Noir Blanc Cassé Daim Cuir Mesh","de":"Zwart Off-White Suède Leer Mesh"}'::jsonb WHERE color_name = 'Black Off-White Suede Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Suède","fr":"Noir Daim","de":"Zwart Suède"}'::jsonb WHERE color_name = 'Black Suede';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Suède Leer","fr":"Noir Daim Cuir","de":"Zwart Suède Leer"}'::jsonb WHERE color_name = 'Black Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Suède Leer Mesh","fr":"Noir Daim Cuir Mesh","de":"Zwart Suède Leer Mesh"}'::jsonb WHERE color_name = 'Black Suede Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Suède Lak","fr":"Noir Daim Vernis","de":"Zwart Suède Lak"}'::jsonb WHERE color_name = 'Black Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Zwart Nubuck","fr":"Bleu Noir Nubuck","de":"Blauw Zwart Nubuck"}'::jsonb WHERE color_name = 'Blue Black Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Zwart Nubuck Leer","fr":"Bleu Noir Nubuck Cuir","de":"Blauw Zwart Nubuck Leer"}'::jsonb WHERE color_name = 'Blue Black Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Zwart Zilver Suède Leer Lak","fr":"Bleu Noir Argent Daim Cuir Vernis","de":"Blauw Zwart Zilver Suède Leer Lak"}'::jsonb WHERE color_name = 'Blue Black Silver Suede Leather Patent';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Grijs Nubuck Leer","fr":"Bleu Gris Nubuck Cuir","de":"Blauw Grijs Nubuck Leer"}'::jsonb WHERE color_name = 'Blue Grey Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Jeans Suède Leer","fr":"Bleu Jeans Daim Cuir","de":"Blauw Jeans Suède Leer"}'::jsonb WHERE color_name = 'Blue Jeans Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Leer","fr":"Bleu Cuir","de":"Blauw Leer"}'::jsonb WHERE color_name = 'Blue Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Leer Nubuck","fr":"Bleu Cuir Nubuck","de":"Blauw Leer Nubuck"}'::jsonb WHERE color_name = 'Blue Leather Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Leer Suède","fr":"Bleu Cuir Daim","de":"Blauw Leer Suède"}'::jsonb WHERE color_name = 'Blue Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Leer Suède Lak","fr":"Bleu Cuir Daim Vernis","de":"Blauw Leer Suède Lak"}'::jsonb WHERE color_name = 'Blue Leather Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Nubuck","fr":"Bleu Nubuck","de":"Blauw Nubuck"}'::jsonb WHERE color_name = 'Blue Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Nubuck Leer","fr":"Bleu Nubuck Cuir","de":"Blauw Nubuck Leer"}'::jsonb WHERE color_name = 'Blue Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Off-White Nubuck","fr":"Bleu Blanc Cassé Nubuck","de":"Blauw Off-White Nubuck"}'::jsonb WHERE color_name = 'Blue Off-White Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Zilver Nubuck","fr":"Bleu Argent Nubuck","de":"Blauw Zilver Nubuck"}'::jsonb WHERE color_name = 'Blue Silver Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Suède","fr":"Bleu Daim","de":"Blauw Suède"}'::jsonb WHERE color_name = 'Blue Suede';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Suède Leer","fr":"Bleu Daim Cuir","de":"Blauw Suède Leer"}'::jsonb WHERE color_name = 'Blue Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Suède Lak","fr":"Bleu Daim Vernis","de":"Blauw Suède Lak"}'::jsonb WHERE color_name = 'Blue Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Zwart Suède Leer","fr":"Marron Noir Daim Cuir","de":"Bruin Zwart Suède Leer"}'::jsonb WHERE color_name = 'Brown Black Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Blauw Suède","fr":"Marron Bleu Daim","de":"Bruin Blauw Suède"}'::jsonb WHERE color_name = 'Brown Blue Suede';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Leer","fr":"Marron Cuir","de":"Bruin Leer"}'::jsonb WHERE color_name = 'Brown Leather';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Leer Nubuck","fr":"Marron Cuir Nubuck","de":"Bruin Leer Nubuck"}'::jsonb WHERE color_name = 'Brown Leather Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Leer Suède","fr":"Marron Cuir Daim","de":"Bruin Leer Suède"}'::jsonb WHERE color_name = 'Brown Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Leer Suède Lak","fr":"Marron Cuir Daim Vernis","de":"Bruin Leer Suède Lak"}'::jsonb WHERE color_name = 'Brown Leather Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Nubuck","fr":"Marron Nubuck","de":"Bruin Nubuck"}'::jsonb WHERE color_name = 'Brown Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Nubuck Leer","fr":"Marron Nubuck Cuir","de":"Bruin Nubuck Leer"}'::jsonb WHERE color_name = 'Brown Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Suède Leer","fr":"Marron Daim Cuir","de":"Bruin Suède Leer"}'::jsonb WHERE color_name = 'Brown Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Zwart Leer","fr":"Cognac Noir Cuir","de":"Cognac Zwart Leer"}'::jsonb WHERE color_name = 'Cognac Black Leather';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Blauw Suède","fr":"Cognac Bleu Daim","de":"Cognac Blauw Suède"}'::jsonb WHERE color_name = 'Cognac Blue Suede';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Fantasie Leer Suède","fr":"Cognac Fantaisie Cuir Daim","de":"Cognac Fantasie Leer Suède"}'::jsonb WHERE color_name = 'Cognac Fantasy Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Leer","fr":"Cognac Cuir","de":"Cognac Leer"}'::jsonb WHERE color_name = 'Cognac Leather';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Leer Suède","fr":"Cognac Cuir Daim","de":"Cognac Leer Suède"}'::jsonb WHERE color_name = 'Cognac Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Suède","fr":"Cognac Daim","de":"Cognac Suède"}'::jsonb WHERE color_name = 'Cognac Suede';
UPDATE products SET color_name_i18n = '{"nl":"Donkerblauw Cognac Leer Suède","fr":"Bleu Foncé Cognac Cuir Daim","de":"Donkerblauw Cognac Leer Suède"}'::jsonb WHERE color_name = 'Dark Blue Cognac Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Donkerblauw Nubuck","fr":"Bleu Foncé Nubuck","de":"Donkerblauw Nubuck"}'::jsonb WHERE color_name = 'Dark Blue Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Donkerblauw Suède","fr":"Bleu Foncé Daim","de":"Donkerblauw Suède"}'::jsonb WHERE color_name = 'Dark Blue Suede';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Zwart Suède Leer","fr":"Marron Foncé Noir Daim Cuir","de":"Donkerbruin Zwart Suède Leer"}'::jsonb WHERE color_name = 'Dark Brown Black Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Leer","fr":"Marron Foncé Cuir","de":"Donkerbruin Leer"}'::jsonb WHERE color_name = 'Dark Brown Leather';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Nubuck","fr":"Marron Foncé Nubuck","de":"Donkerbruin Nubuck"}'::jsonb WHERE color_name = 'Dark Brown Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Suède","fr":"Marron Foncé Daim","de":"Donkerbruin Suède"}'::jsonb WHERE color_name = 'Dark Brown Suede';
UPDATE products SET color_name_i18n = '{"nl":"Fuchsia Bruin Multi Suède","fr":"Fuchsia Marron Multi Daim","de":"Fuchsia Bruin Multi Suède"}'::jsonb WHERE color_name = 'Fuchsia Brown Multi Suede';
UPDATE products SET color_name_i18n = '{"nl":"Groen Taupe Multi Suède","fr":"Vert Taupe Multi Daim","de":"Groen Taupe Multi Suède"}'::jsonb WHERE color_name = 'Green Taupe Multi Suede';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Antraciet Suède","fr":"Gris Anthracite Daim","de":"Grijs Antraciet Suède"}'::jsonb WHERE color_name = 'Grey Anthracite Suede';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Zwart Nubuck Leer","fr":"Gris Noir Nubuck Cuir","de":"Grijs Zwart Nubuck Leer"}'::jsonb WHERE color_name = 'Grey Black Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Zwart Suède","fr":"Gris Noir Daim","de":"Grijs Zwart Suède"}'::jsonb WHERE color_name = 'Grey Black Suede';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Leer Suède","fr":"Gris Cuir Daim","de":"Grijs Leer Suède"}'::jsonb WHERE color_name = 'Grey Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Multi Kleur Suède Leer Mesh","fr":"Gris Multicolore Daim Cuir Mesh","de":"Grijs Multi Kleur Suède Leer Mesh"}'::jsonb WHERE color_name = 'Grey Multi Colour Suede Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Suède Leer","fr":"Gris Daim Cuir","de":"Grijs Suède Leer"}'::jsonb WHERE color_name = 'Grey Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Jeans Leer Suède","fr":"Jeans Cuir Daim","de":"Jeans Leer Suède"}'::jsonb WHERE color_name = 'Jeans Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Kaki Zwart Suède Leer Mesh","fr":"Kaki Noir Daim Cuir Mesh","de":"Kaki Zwart Suède Leer Mesh"}'::jsonb WHERE color_name = 'Kaki Black Suede Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Off-White Fantasie Leer","fr":"Blanc Cassé Fantaisie Cuir","de":"Off-White Fantasie Leer"}'::jsonb WHERE color_name = 'Off-White Fantasy Leather';
UPDATE products SET color_name_i18n = '{"nl":"Off-White Multi Kleur Suède Leer Nubuck","fr":"Blanc Cassé Multicolore Daim Cuir Nubuck","de":"Off-White Multi Kleur Suède Leer Nubuck"}'::jsonb WHERE color_name = 'Off-White Multi Colour Suede Leather Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Off-White Nubuck Leer","fr":"Blanc Cassé Nubuck Cuir","de":"Off-White Nubuck Leer"}'::jsonb WHERE color_name = 'Off-White Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Off-White Slangenleer","fr":"Blanc Cassé Serpent Cuir","de":"Off-White Slangenleer"}'::jsonb WHERE color_name = 'Off-White Snake Leather';
UPDATE products SET color_name_i18n = '{"nl":"Off-White Suède Leer Mesh","fr":"Blanc Cassé Daim Cuir Mesh","de":"Off-White Suède Leer Mesh"}'::jsonb WHERE color_name = 'Off-White Suede Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Oker Zwart Nubuck Leer","fr":"Ocre Noir Nubuck Cuir","de":"Oker Zwart Nubuck Leer"}'::jsonb WHERE color_name = 'Oker Black Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Oker Bruin Nubuck","fr":"Ocre Marron Nubuck","de":"Oker Bruin Nubuck"}'::jsonb WHERE color_name = 'Oker Brown Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Olijfgroen Zwart Nubuck","fr":"Vert Olive Noir Nubuck","de":"Olijfgroen Zwart Nubuck"}'::jsonb WHERE color_name = 'Olive Green Black Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Olijfgroen Zwart Nubuck Leer","fr":"Vert Olive Noir Nubuck Cuir","de":"Olijfgroen Zwart Nubuck Leer"}'::jsonb WHERE color_name = 'Olive Green Black Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Olijfgroen Nubuck","fr":"Vert Olive Nubuck","de":"Olijfgroen Nubuck"}'::jsonb WHERE color_name = 'Olive Green Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Olijf Suède","fr":"Olive Daim","de":"Olijf Suède"}'::jsonb WHERE color_name = 'Olive Suede';
UPDATE products SET color_name_i18n = '{"nl":"Olijf Taupe Suède","fr":"Olive Taupe Daim","de":"Olijf Taupe Suède"}'::jsonb WHERE color_name = 'Olive Taupe Suede';
UPDATE products SET color_name_i18n = '{"nl":"Roze Leer Suède","fr":"Rose Cuir Daim","de":"Roze Leer Suède"}'::jsonb WHERE color_name = 'Pink Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Rood Leer Suède","fr":"Rouge Cuir Daim","de":"Rood Leer Suède"}'::jsonb WHERE color_name = 'Red Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Rood Nubuck","fr":"Rouge Nubuck","de":"Rood Nubuck"}'::jsonb WHERE color_name = 'Red Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Zwart Nubuck Mesh","fr":"Taupe Noir Nubuck Mesh","de":"Taupe Zwart Nubuck Mesh"}'::jsonb WHERE color_name = 'Taupe Black Nubuck Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Zwart Suède Leer","fr":"Taupe Noir Daim Cuir","de":"Taupe Zwart Suède Leer"}'::jsonb WHERE color_name = 'Taupe Black Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Zwart Suède Leer Lak","fr":"Taupe Noir Daim Cuir Vernis","de":"Taupe Zwart Suède Leer Lak"}'::jsonb WHERE color_name = 'Taupe Black Suede Leather Patent';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Bruin Nubuck Leer","fr":"Taupe Marron Nubuck Cuir","de":"Taupe Bruin Nubuck Leer"}'::jsonb WHERE color_name = 'Taupe Brown Nubuck Leather';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Goud Leer","fr":"Taupe Or Cuir","de":"Taupe Goud Leer"}'::jsonb WHERE color_name = 'Taupe Gold Leather';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Leer","fr":"Taupe Cuir","de":"Taupe Leer"}'::jsonb WHERE color_name = 'Taupe Leather';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Leer Nubuck","fr":"Taupe Cuir Nubuck","de":"Taupe Leer Nubuck"}'::jsonb WHERE color_name = 'Taupe Leather Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Leer Suède","fr":"Taupe Cuir Daim","de":"Taupe Leer Suède"}'::jsonb WHERE color_name = 'Taupe Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Leer Suède Lak","fr":"Taupe Cuir Daim Vernis","de":"Taupe Leer Suède Lak"}'::jsonb WHERE color_name = 'Taupe Leather Suede Patent';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Nubuck","fr":"Taupe Nubuck","de":"Taupe Nubuck"}'::jsonb WHERE color_name = 'Taupe Nubuck';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Nubuck Mesh Lak","fr":"Taupe Nubuck Mesh Vernis","de":"Taupe Nubuck Mesh Lak"}'::jsonb WHERE color_name = 'Taupe Nubuck Mesh Patent';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Suède Leer","fr":"Taupe Daim Cuir","de":"Taupe Suède Leer"}'::jsonb WHERE color_name = 'Taupe Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Taupe Wit Suède Leer","fr":"Taupe Blanc Daim Cuir","de":"Taupe Wit Suède Leer"}'::jsonb WHERE color_name = 'Taupe White Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Wit Zwart Leer","fr":"Blanc Noir Cuir","de":"Wit Zwart Leer"}'::jsonb WHERE color_name = 'White Black Leather';
UPDATE products SET color_name_i18n = '{"nl":"Wit Zwart Leer Mesh","fr":"Blanc Noir Cuir Mesh","de":"Wit Zwart Leer Mesh"}'::jsonb WHERE color_name = 'White Black Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Wit Fantasie Leer","fr":"Blanc Fantaisie Cuir","de":"Wit Fantasie Leer"}'::jsonb WHERE color_name = 'White Fantasy Leather';
UPDATE products SET color_name_i18n = '{"nl":"Wit Fantasie Petrol Leer Suède","fr":"Blanc Fantaisie Pétrole Cuir Daim","de":"Wit Fantasie Petrol Leer Suède"}'::jsonb WHERE color_name = 'White Fantasy Petrol Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Wit Leer","fr":"Blanc Cuir","de":"Wit Leer"}'::jsonb WHERE color_name = 'White Leather';
UPDATE products SET color_name_i18n = '{"nl":"Wit Leer Mesh","fr":"Blanc Cuir Mesh","de":"Wit Leer Mesh"}'::jsonb WHERE color_name = 'White Leather Mesh';
UPDATE products SET color_name_i18n = '{"nl":"Wit Leer Suède","fr":"Blanc Cuir Daim","de":"Wit Leer Suède"}'::jsonb WHERE color_name = 'White Leather Suede';
UPDATE products SET color_name_i18n = '{"nl":"Wit Multi Kleur Suède Leer","fr":"Blanc Multicolore Daim Cuir","de":"Wit Multi Kleur Suède Leer"}'::jsonb WHERE color_name = 'White Multi Colour Suede Leather';
UPDATE products SET color_name_i18n = '{"nl":"Fuchsia Combi","fr":"Fuchsia Combi","de":"Fuchsia Combi"}'::jsonb WHERE color_name = 'Fuchsia Combi';
UPDATE products SET color_name_i18n = '{"nl":"Kobaltblauw Combi","fr":"Cobalt Combi","de":"Kobaltblauw Combi"}'::jsonb WHERE color_name = 'Cobalt Combi';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Combi","fr":"Noir Combi","de":"Zwart Combi"}'::jsonb WHERE color_name = 'Black Combi';
UPDATE products SET color_name_i18n = '{"nl":"Wit Kobaltblauw Combi","fr":"Blanc Cobalt Combi","de":"Wit Kobaltblauw Combi"}'::jsonb WHERE color_name = 'White Cobalt Combi';
UPDATE products SET color_name_i18n = '{"nl":"Wit Blauw Combi","fr":"Blanc Bleu Combi","de":"Wit Blauw Combi"}'::jsonb WHERE color_name = 'White Blue Combi';
UPDATE products SET color_name_i18n = '{"nl":"Paars Combi","fr":"Violet Combi","de":"Paars Combi"}'::jsonb WHERE color_name = 'Purple Combi ';
UPDATE products SET color_name_i18n = '{"nl":"Donkerblauw Combi","fr":"Bleu Foncé Combi","de":"Donkerblauw Combi"}'::jsonb WHERE color_name = 'Dark Blue Combi';
UPDATE products SET color_name_i18n = '{"nl":"Wit Combi","fr":"Blanc Combi","de":"Wit Combi"}'::jsonb WHERE color_name = 'White Combi';
UPDATE products SET color_name_i18n = '{"nl":"Khaki","fr":"Khaki","de":"Khaki"}'::jsonb WHERE color_name = 'Dark Green';
UPDATE products SET color_name_i18n = '{"nl":"Donkerblauw","fr":"Bleu Foncé","de":"Donkerblauw"}'::jsonb WHERE color_name = 'Dark Blue';
UPDATE products SET color_name_i18n = '{"nl":"Legergroen Fantasie","fr":"Armée Fantaisie","de":"Legergroen Fantasie"}'::jsonb WHERE color_name = 'Army Fantasy';
UPDATE products SET color_name_i18n = '{"nl":"Fuchsia","fr":"Fuchsia","de":"Fuchsia"}'::jsonb WHERE color_name = 'Fuchsia';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin","fr":"Marron Foncé","de":"Donkerbruin"}'::jsonb WHERE color_name = 'Dark Brown';
UPDATE products SET color_name_i18n = '{"nl":"Zacht Roze","fr":"Rose Doux","de":"Zacht Roze"}'::jsonb WHERE color_name = 'Soft Pink ';
UPDATE products SET color_name_i18n = '{"nl":"Lila","fr":"Lilas","de":"Lila"}'::jsonb WHERE color_name = 'Lilac';
UPDATE products SET color_name_i18n = '{"nl":"Groen","fr":"Vert","de":"Groen"}'::jsonb WHERE color_name = 'Green';
UPDATE products SET color_name_i18n = '{"nl":"Mint","fr":"Menthe","de":"Mint"}'::jsonb WHERE color_name = 'Mint';
UPDATE products SET color_name_i18n = '{"nl":"Zwart/Wit","fr":"Noir/Blanc","de":"Zwart/Wit"}'::jsonb WHERE color_name = 'Black/White ';
UPDATE products SET color_name_i18n = '{"nl":"Camel Combi","fr":"Camel Combi","de":"Camel Combi"}'::jsonb WHERE color_name = 'Camel Combi';
UPDATE products SET color_name_i18n = '{"nl":"Kobalti Combi","fr":"Cobalt Combi","de":"Kobalti Combi"}'::jsonb WHERE color_name = 'Cobalti Combi';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Geel Combi","fr":"Noir Jaune Combi","de":"Zwart Geel Combi"}'::jsonb WHERE color_name = 'Black Yellow Combi';
UPDATE products SET color_name_i18n = '{"nl":"Zwart/Fuchsia Combi","fr":"Noir/Fuchsia Combi","de":"Zwart/Fuchsia Combi"}'::jsonb WHERE color_name = 'Black/Fuchsia Combi';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Fantasie","fr":"Marron Foncé Fantaisie","de":"Donkerbruin Fantasie"}'::jsonb WHERE color_name = 'Dark Brown Fantasy';
UPDATE products SET color_name_i18n = '{"nl":"Tan","fr":"Tan","de":"Tan"}'::jsonb WHERE color_name = 'Tan ';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Fantasie","fr":"Bleu Fantaisie","de":"Blauw Fantasie"}'::jsonb WHERE color_name = 'Blue Fantasy';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Reptielprint","fr":"Noir Imprimé Reptile","de":"Zwart Reptielprint"}'::jsonb WHERE color_name = 'Black Reptile Print';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Fuchsia Combi","fr":"Noir Fuchsia Combi","de":"Zwart Fuchsia Combi"}'::jsonb WHERE color_name = 'Black Fuchsia Combi';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Fantasie Pony","fr":"Cognac Fantaisie Poney","de":"Cognac Fantasie Pony"}'::jsonb WHERE color_name = 'Cognac Fantasy Pony ';
UPDATE products SET color_name_i18n = '{"nl":"Multi Kleur Fantasie Print","fr":"Multicolore Fantaisie Imprimé","de":"Multi Kleur Fantasie Print"}'::jsonb WHERE color_name = 'Multi Colour Fantasy Print';
UPDATE products SET color_name_i18n = '{"nl":"Blauw Fantasie Print","fr":"Bleu Fantaisie Imprimé","de":"Blauw Fantasie Print"}'::jsonb WHERE color_name = 'Blue Fantasy Print';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Fantasie Pony","fr":"Gris Fantaisie Poney","de":"Grijs Fantasie Pony"}'::jsonb WHERE color_name = 'Grey Fantasy Pony';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Lak","fr":"Noir Vernis","de":"Zwart Lak"}'::jsonb WHERE color_name = 'Black Patent';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Bloemenprint","fr":"Noir Imprimé Fleur","de":"Zwart Bloemenprint"}'::jsonb WHERE color_name = 'Black Flower Print';
UPDATE products SET color_name_i18n = '{"nl":"Zwart City Light Lak","fr":"Noir City Light Vernis","de":"Zwart City Light Lak"}'::jsonb WHERE color_name = 'Black City Light Patent';
UPDATE products SET color_name_i18n = '{"nl":"Wit Fantasie Regenboog","fr":"Blanc Fantaisie Arc-en-Ciel","de":"Wit Fantasie Regenboog"}'::jsonb WHERE color_name = 'White Fantasy Rainbow';
UPDATE products SET color_name_i18n = '{"nl":"Zwart/Goud Fantasie Print Suède","fr":"Noir/Or Fantaisie Imprimé Daim","de":"Zwart/Goud Fantasie Print Suède"}'::jsonb WHERE color_name = 'Black/Gold Fantasy Print Suede';
UPDATE products SET color_name_i18n = '{"nl":"Groen/Blauw Lak","fr":"Vert/Bleu Vernis","de":"Groen/Blauw Lak"}'::jsonb WHERE color_name = 'Green/Blue Patent';
UPDATE products SET color_name_i18n = '{"nl":"Baby Roze","fr":"Rose Bébé","de":"Baby Roze"}'::jsonb WHERE color_name = 'Baby Pink ';
UPDATE products SET color_name_i18n = '{"nl":"Champagne Metallic","fr":"Champagne Métallisé","de":"Champagne Metallic"}'::jsonb WHERE color_name = 'Champagne Metalize';
UPDATE products SET color_name_i18n = '{"nl":"Fantasie Suède","fr":"Daim Fantaisie","de":"Fantasie Suède"}'::jsonb WHERE color_name = 'Fantasy Suede';
UPDATE products SET color_name_i18n = '{"nl":"Bruin","fr":"Marron","de":"Bruin"}'::jsonb WHERE color_name = 'Brown';
UPDATE products SET color_name_i18n = '{"nl":"Kobaltblauw","fr":"Bleu Cobalt","de":"Kobaltblauw"}'::jsonb WHERE color_name = 'Cobalt Blue';
UPDATE products SET color_name_i18n = '{"nl":"Blauw","fr":"Bleu","de":"Blauw"}'::jsonb WHERE color_name = 'Blue';
UPDATE products SET color_name_i18n = '{"nl":"Rood","fr":"Rouge","de":"Rood"}'::jsonb WHERE color_name = 'Red';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin Combi","fr":"Marron Foncé Combi","de":"Donkerbruin Combi"}'::jsonb WHERE color_name = 'Dark Brown Combi';
UPDATE products SET color_name_i18n = '{"nl":"Rood Combi","fr":"Rouge Combi","de":"Rood Combi"}'::jsonb WHERE color_name = 'Red Combi';
UPDATE products SET color_name_i18n = '{"nl":"Grijs","fr":"Gris","de":"Grijs"}'::jsonb WHERE color_name = 'Grey';
UPDATE products SET color_name_i18n = '{"nl":"Paars","fr":"Violet","de":"Paars"}'::jsonb WHERE color_name = 'Purple';
UPDATE products SET color_name_i18n = '{"nl":"Fantasie","fr":"Fantaisie","de":"Fantasie"}'::jsonb WHERE color_name = 'Fantasy';
UPDATE products SET color_name_i18n = '{"nl":"Tan","fr":"Tan","de":"Tan"}'::jsonb WHERE color_name = 'Tan';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Reptielprint","fr":"Noir Imprimé Reptile","de":"Zwart Reptielprint"}'::jsonb WHERE color_name = 'Balck Reptile Print';
UPDATE products SET color_name_i18n = '{"nl":"Cognac Fantasie Pony","fr":"Cognac Fantaisie Poney","de":"Cognac Fantasie Pony"}'::jsonb WHERE color_name = 'Cognac Fantasy Pony';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Bloemenprint","fr":"Noir Imprimé Fleur","de":"Zwart Bloemenprint"}'::jsonb WHERE color_name = 'Black Flower Print ';
UPDATE products SET color_name_i18n = '{"nl":"Zwart/Goud Fantasie Print","fr":"Noir/Or Fantaisie Imprimé","de":"Zwart/Goud Fantasie Print"}'::jsonb WHERE color_name = 'Black/Gold Fantasy Print';
UPDATE products SET color_name_i18n = '{"nl":"Camel","fr":"Camel","de":"Camel"}'::jsonb WHERE color_name = 'Camel';
UPDATE products SET color_name_i18n = '{"nl":"Bruin Geolied","fr":"Marron Huilé","de":"Bruin Geolied"}'::jsonb WHERE color_name = 'Brown oiled';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Geolied","fr":"Noir Huilé","de":"Zwart Geolied"}'::jsonb WHERE color_name = 'Black oiled';
UPDATE products SET color_name_i18n = '{"nl":"Off-White","fr":"Blanc Cassé","de":"Off-White"}'::jsonb WHERE color_name = 'Off White ';
UPDATE products SET color_name_i18n = '{"nl":"Zwart/Goud","fr":"Noir/Or","de":"Zwart/Goud"}'::jsonb WHERE color_name = 'Black/Gold';
UPDATE products SET color_name_i18n = '{"nl":"Marineblauw","fr":"Marine","de":"Marineblauw"}'::jsonb WHERE color_name = 'Navy';
UPDATE products SET color_name_i18n = '{"nl":"Wit Fantasie Regenboog","fr":"Blanc Fantaisie Arc-en-Ciel","de":"Wit Fantasie Regenboog"}'::jsonb WHERE color_name = 'White Fantasy Rainbow ';
UPDATE products SET color_name_i18n = '{"nl":"Beige Mint Combi","fr":"Beige Menthe Combi","de":"Beige Mint Combi"}'::jsonb WHERE color_name = 'Beige Mint Combi';
UPDATE products SET color_name_i18n = '{"nl":"Donkerbruin","fr":"Marron Foncé","de":"Donkerbruin"}'::jsonb WHERE color_name = 'Dark Brown ';
UPDATE products SET color_name_i18n = '{"nl":"Wit Regenboog Fantasie","fr":"Blanc Arc-en-Ciel Fantaisie","de":"Wit Regenboog Fantasie"}'::jsonb WHERE color_name = 'White Rainbow Fantasy';
UPDATE products SET color_name_i18n = '{"nl":"Grijs Combi","fr":"Gris Combi","de":"Grijs Combi"}'::jsonb WHERE color_name = 'Grey Combi';
UPDATE products SET color_name_i18n = '{"nl":"Antraciet Rood","fr":"Anthracite Rouge","de":"Antraciet Rood"}'::jsonb WHERE color_name = 'Anthracite Red';
UPDATE products SET color_name_i18n = '{"nl":"Zwart Grijs","fr":"Noir Gris","de":"Zwart Grijs"}'::jsonb WHERE color_name = 'Black Grey';
UPDATE products SET color_name_i18n = '{"nl":"Wit, Rood","fr":"Blanc, Rouge","de":"Wit, Rood"}'::jsonb WHERE color_name = 'White, Red';
UPDATE products SET color_name_i18n = '{"nl":"Beige, Multi Kleur","fr":"Beige, Multicolore","de":"Beige, Multi Kleur"}'::jsonb WHERE color_name = 'Beige, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Zwart, Grijs","fr":"Noir, Gris","de":"Zwart, Grijs"}'::jsonb WHERE color_name = 'Black, Grey';
UPDATE products SET color_name_i18n = '{"nl":"Zwart, Multi Kleur","fr":"Noir, Multicolore","de":"Zwart, Multi Kleur"}'::jsonb WHERE color_name = 'Black, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Blauw, Multi Kleur","fr":"Bleu, Multicolore","de":"Blauw, Multi Kleur"}'::jsonb WHERE color_name = 'Blue, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Bruin, Multi Kleur","fr":"Marron, Multicolore","de":"Bruin, Multi Kleur"}'::jsonb WHERE color_name = 'brown, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Fuchsia, Multi Kleur","fr":"Fuchsia, Multicolore","de":"Fuchsia, Multi Kleur"}'::jsonb WHERE color_name = 'Fuchsia, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Groen, Multi Kleur","fr":"Vert, Multicolore","de":"Groen, Multi Kleur"}'::jsonb WHERE color_name = 'Green, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Grijs, Multi Kleur","fr":"Gris, Multicolore","de":"Grijs, Multi Kleur"}'::jsonb WHERE color_name = 'Grey, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Grijs, Rood","fr":"Gris, Rouge","de":"Grijs, Rood"}'::jsonb WHERE color_name = 'Grey, Red';
UPDATE products SET color_name_i18n = '{"nl":"Multi Kleur","fr":"Multicolore","de":"Multi Kleur"}'::jsonb WHERE color_name = 'Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Roze","fr":"Rose","de":"Roze"}'::jsonb WHERE color_name = 'Pink';
UPDATE products SET color_name_i18n = '{"nl":"Roze, Multi Kleur","fr":"Rose, Multicolore","de":"Roze, Multi Kleur"}'::jsonb WHERE color_name = 'Pink, Multi Colour';
UPDATE products SET color_name_i18n = '{"nl":"Paars, Multi Kleur","fr":"Violet, Multicolore","de":"Paars, Multi Kleur"}'::jsonb WHERE color_name = 'Purple, Multi colour';
UPDATE products SET color_name_i18n = '{"nl":"Wit, Multi Kleur","fr":"Blanc, Multicolore","de":"Wit, Multi Kleur"}'::jsonb WHERE color_name = 'White, Multi Colour';

-- Report
SELECT COUNT(*) as total_colors_updated FROM products WHERE color_name_i18n IS NOT NULL;
